pub(crate) mod connection_controls;
pub mod leftbar;
pub(crate) mod machine_controls;
pub(crate) mod operationslist;
pub(crate) mod repeat_button;
pub mod rightbar;
pub mod statusbar;
pub(crate) mod topbar;
pub mod workspace;
